export enum AppRoutes {
    Home = '/',
    SignIn = '/signIn',
    Appointments = '/appointments',
    CreateAppointment = '/appointments/create',
    RescheduleAppointment = '/appointments/:id/reschedule',
    Doctors = '/doctors',
    CreateDoctor = '/doctors/create',
    DoctorProfile = '/doctors/:id/profile',
    Offices = '/offices',
    CreateOffice = '/offices/create',
    OfficeInformation = '/offices/:id',
    Profile = '/profile',
    Specializations = '/specializations',
    CreateSpecialization = '/specializations/create',
    SpecializationInformation = '/specializations/:id',
}
