export enum EventType {
    CLOSE_MODAL = 'closeModal',
    CLICK_CLOSE_MODAL = 'switchModal',
    SHOW_POPUP = 'showPopup',
    DECLINE_DIALOG = 'declineDialog',
    SUBMIT_DIALOG = 'submitDialog',
    ENTER_TIMESLOT = 'enterTimeslot',
    OPEN_AUTOCOMPLETE = 'openAutocomplete',
    AUTOCOMPLETE_INPUT_CHANGE = 'autocompleteInputChange',
    AUTOCOMPLETE_VALUE_CHANGE = 'autocompleteValueChange',
    SWITCH_ASIDE = 'switchAside',
    OPEN_TIMEPICKER = 'openTimePicker',
    TIMEPICKER_VALUE_CHANGE = 'timePickerValueChange',
    DATEPICKER_VALUE_CHANGE = 'datePickerValueChange',
}
